language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
if: branch IN (master, development, features)
before_install:
- npm install -g typescript
before_script:
- npm run setup
- npm run build:client
- npm run build:server
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: XhcinjJQnZjwrkVla1EKPV1HeWPDpiqxf6kYnQW5ZhBifdSBXw8XB1+Wj9+69c7mq78dKbkxQah8lM9LFw2yUwoMAuujYwPcMVwicEwpz3ut6BF9XD/5aN3jjgj64uHtChHsBiVJqhVhJw7ujphppUaZa0DDc+1nBG+KHzh3f9cZJEEngX4niy03VfNm0EhocNfw8BG4s9gyPeON+zuF4Kai+9adt/ld+5P2NQ9fo/WA4nU39btBf3VwCsIz8KHT5Z7kqYqMVRDedeZDEdaDj6tHOQrT5QPi/Fy0AxljWEpjLeuHHfvqp6i5nDMXQXoEqlEfnqpBS2C2E5njCA6U+A02hGZoREHokw06ql+7dszeps0YuGaevgmjvbSEHv921sLsJdREJeyNnpOLHWBnOfPJcuG0g180u84N+/4a7OjBDXBje6QWX6+iHDsZw9WxBG78TXwT2954myuNkgNj8R+sHRu5kcUlIXAoqm6IyKJKLIEddijhB4t0sjNRvqbdODKulW926AllQg6j7UCdDDzKXH8X7G61rz8GVgjLNZ2HDR30GfGOiqvcaP/dfERDjPC0PZLYVU8mpWSypLqS9EeeAH1fa0v7DWd7mrtPuVXfpV7IRP8FWD23Vgx3QKokgDBlCGhzBgTTmFFhtKi07ZrD0WzIFrwKurpn7OmfUGs=
  app: bears-ims
  on:
    repo: chingu-voyage3/bears-10
