language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
if: branch IN (master, development, features)
before_install:
- npm install -g typescript
before_script:
- npm run setup
- npm run build:client
- npm run build:server
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: o8iKUsJC3IotmaWBVy4jYHVwYxWitl/TjRMy/HjOLTHTMIPfBSj8GvcZpeQlPfqisOYrQjpyctLpaayIvnnYyt4/mWSE9yZvKBkKafsqVVQ4v4JKYLB6nsN9BAIi4Xrg6qkeqSylTjrshmYmL18c3RvvYAIm8MnNpC7CAg1xEnyJY5HzUWceJj4pU1U9wt25loXWkN+hLHhuF+8OnBJfB3d5yTDFSrh4i75+AzaO0tZsK71K6pyBZZ5KZAXGZcaDqB2+cegLR5d7KWtlyG1I98gg9o5L3nm2Z1vQUNfwQ+uf2/PnLH0+HrLpAu1gRXYP7SVQEF35TT5YwkL1SF2Q0Xge//eOaRnXkI4AqUYiaFf7Y1h4lf1ejjyRCkrQGHGEP8y/X55FTH2YPYdmj74Rkm4Gi6W8G6pgUtjTzQjPLf4IsP/YgA6cMii2B7x5m9mcQkUC8UWMzkCRZVJUSPDFfT31dMbAf18ltGhY+exAYOilbRKF7SqrjW/do9AeQlL+nTi9XyNBuys+CQ4WHvNGEgMROUOdEfoH/khe2C9C/JcVJvOme2hFIVSjHNbHYp7hD4vQ+lhONrdcTiDnDk2hVM4/d7qqv+hRzv2DLxLVuBwYviAzV/AhoAdIga+lnU6IZ6D+0Aon+60LRdXB5fwEmn29RsSlIU5tkl88urSUYa8=
  app: bears-ims
  on:
    repo: chingu-voyage3/bears-10
