language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
if: branch IN (master, development, features)
before_install:
- npm install -g typescript
before_script:
- npm run setup
- npm run build:client
- npm run build:server
deploy:
  provider: heroku
  api_key:
    secure: kzBFj7SP0emIR9OFLYKSGC+RNYAjSyhMtlvC59RdSRCBd6L54lm6l8G18m3H55vWTWNeCZG1Ihs+gyggIIgg+VCXwza1xuDXf3AHqjlAha5PRxnLrYu4Rwy8+ReTWkyhRQgURYPfJBfYuxNRsDlkwBCi0TExun2XSeV5X59mFdQFLCMGm1ZEhOOqbnYke4LybDvano0+mg4nWFx+umJq7rYzAXI3JiFq7/pOLlEeqfEi4Yir2dks27U4nTTOlLQHn4owQNrn/pQBqP7oZm0US7d1+vfxWpugX32xR97sCgTNbIzLW+GKf4o7YwsiwRSalc/RjTqo/MuLy493tjQHmljzkWeu3Hbpd6KpuDDQrU2QRbWDcvFfjnrvBTc+XcyDlnLIKt9FmXB9WO1IBN7p5xaPE0FC1Do/GFVXqhwfPLjdhjKcOFHycqa7MDfv1C0DCYM/O2ixy1M/SpISKMUSv/mTUz0zHH8VrfxNjctzMr0zL5gpjCY90OEUKfuP9UQI2XBcwN80nPL63Qas0Q4ddPJWKmT8nruZxXTOLAl18q27sKM+vtAyASqQHXW7JDLRYYFrIJDqIWFV6W6mveolT8HRg/MEOuH/fni1F27Gjc83HSaKLHJI+vBlWxPW6TXoxB2ZLCUwSqlVAEKrB8AmbspAavTOwPiWquBRWsLpUqk=
  app: bears-ims
  on:
    repo: chingu-voyage3/bears-10
