language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
if: branch IN (master, development, features)
before_install:
- npm install -g typescript
before_script:
- npm run setup
- npm run build:client
- npm run build:server
deploy:
  provider: heroku
  api_key:
    secure: kPBwIa/J57ONcua9PVKy0OJhdNo//anMmqhO+lHfMhjAJYnoh4Xrii02b5SPmDZkYAMA/TF6iLECsBMuvDgBcMaiv0EN8HZteUIXP0vPVeWoFsD4x+IzD6r2zcUBmQO8pTE+mgeIllMA/rbLeGmFc9zZlXcHHn3comkTgh/xv/99ubNKtGGNvCPsYJc/v3pdMvMBfBkOA/WJEFOZYc4CNmueuHfeoBEbhQw16vHngd9Hr0cVevOk8NPuhOLuYOvP5T80ScgMSGvBQD6G5v1aUPUkR6WwVktpO5p+8zbUx6b3825HB0Ok+hBodbzJfdMLWqWfgRnuqsniEItzgLbDdUE2h5l/Okj73V7OmYCi1HBZWj2RrDYa+HBM4wZO9hx0MJNUuo5J5RtT6YXG7TSOCjkxgPp7RvoL6RHUdxaVlOZ+AB7AmcBdxlTr/ZAfJyKB6pVYrw4sKQpYDXYclQDC7kudnqL0c+NAb9qz0aCR3WePH3BBZ6tgNi3T5FXhdIaTEiPWXW1ZTcSHh1RRexQayVM+haj+5kM6bBonjYYW3sTBwo74g7htdjO3qSpcRdHeYlsx2LXFrqtpJWhu0UxHFnmFz0bfuVOTa7oi5B9oDy/+69ygrap2QUIAhxEBLIwtuj91M2nS9l/6gni3otfzQkfUuBnnr5Q0CFa0LbMlHwI=
  app: bears-ims
  on:
    repo: chingu-voyage3/bears-10
