language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
if: branch IN (master, development, features)
before_install:
- npm install -g typescript
before_script:
- npm run setup
- npm run build:client
- npm run build:server
deploy:
  provider: heroku
  api_key:
    secure: JVeIqMi+0fEYgtaAMrHOfQdLk5AvJ+d1poFI99YN1cbCMuXJAARUBxcdjWbBDOV1+HU6qfOhbYB/rUTKOpdK7Egvs/OZDq4PWrP9ubi4WY4IyRTYYSXAdwg1xNfEtKdFTgXA0RRXLgYbb5kLU8SS7qd1A5Y+daHLHpZhhg9HJSG1ke91UFNPPSp7iNmLYKdLLQbr460qU+DWj9dPBXp7QOSEE1+xdJATKP52erdo8KblCoVEe/AMsouWfMGoPVdemS6i0NJj763S0+GM4lP0BZc/Fw+qNQJ2nGZUrCbbjXpUbX9gPlL+p/PN60spjwPTsU9oVwC+XPVQeqrBjQ3MpFM2yyuXP4APQSrshNAbqtviCD3sSaU9xPpqgHfNvGzKuojLPJntPBknjMBni5hkjpcdAcQ9KOgLeI135Y+kzQ2FiNUYs3D64Ktr8GYSICORkC2TSum3SCQrsZwTYEHgWqVxFagrc+cGxTXfbWPXU2uq4T8obVAc+rV3mBp0/iCPT0ZzmcuG3gvjLl2QGoVgXxBoYMuQ+gDu5L+tD4GzPlyP0MpB/9i2lUL4Yfmag8x2cugMgPOy7bYNzjSFoCCGuhYqTxx9nCXjUDziaqugUBxVJD8UveGlX5PsyfZE4KiFXx15e+XYNdq+VpuPlD1vJV0959oTXvvmgU78SvHEKH4=
  app: bears-ims
  on:
    repo: chingu-voyage3/bears-10
  skip_cleanup: true
